// One-time bootstrap importer (run locally, not in CI).
// Copies IntroSlider/2048/NN TITLE - CLIENT NAME.jpg into
// site/src/assets/hero/NN-slug.jpg and emits site/src/data/hero.data.ts
// (title + client per slide). Hero.astro globs the images and sorts by
// the leading NN, newest (highest number) first.
// Usage: node scripts/import-hero.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SITE_ROOT = path.resolve(__dirname, "..");
const REPO_ROOT = path.resolve(SITE_ROOT, "..");
const SRC_DIR = path.join(REPO_ROOT, "IntroSlider/2048");
const OUT_DIR = path.join(SITE_ROOT, "src/assets/hero");
const DATA_OUT = path.join(SITE_ROOT, "src/data/hero.data.ts");

const ACRONYMS = new Set(["BR", "NYE", "FC", "CES", "IFA", "CLT", "PWR"]);
const WORD_OVERRIDES = { ACDC: "AC/DC" };

function titleCase(s) {
  const lower = new Set(["of", "the", "and", "at", "in", "a"]);
  return s
    .toLowerCase()
    .split(/\s+/)
    .map((w, i) => {
      const upper = w.toUpperCase();
      if (WORD_OVERRIDES[upper]) return WORD_OVERRIDES[upper];
      if (ACRONYMS.has(upper)) return upper;
      if (i > 0 && lower.has(w)) return w;
      return w[0].toUpperCase() + w.slice(1);
    })
    .join(" ");
}

function slugify(s) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const files = fs
    .readdirSync(SRC_DIR)
    .filter((f) => /\.(jpe?g|png|webp)$/i.test(f) && !f.startsWith("."));

  const records = [];
  for (const f of files) {
    const m = f.match(/^(\d{2})\s+(.+?)\s*[-_]\s*CLIENT\s+(.+)\.(jpe?g|png|webp)$/i);
    if (!m) {
      console.warn(`!! couldn't parse: ${f}`);
      continue;
    }
    const [, nn, rawTitle, rawClient, ext] = m;
    const title = titleCase(rawTitle.trim());
    const client = titleCase(rawClient.trim());
    const slug = `${nn}-${slugify(rawTitle)}`;
    const outName = `${slug}.jpg`;
    const outPath = path.join(OUT_DIR, outName);
    if (!fs.existsSync(outPath)) {
      fs.copyFileSync(path.join(SRC_DIR, f), outPath);
    }
    records.push({ nn, slug: outName, title, client });
  }

  records.sort((a, b) => Number(b.nn) - Number(a.nn));

  const lines = [];
  lines.push("// Hero slide text data. Generated by scripts/import-hero.mjs, then hand-edited.");
  lines.push("// Add a future slide: drop NN TITLE - CLIENT NAME.jpg into IntroSlider/2048,");
  lines.push("// re-run the importer, and re-check the order/text below.");
  lines.push("export interface HeroSlideData {");
  lines.push("  file: string;");
  lines.push("  project: string;");
  lines.push("  client: string;");
  lines.push("}");
  lines.push("");
  lines.push("export const heroSlidesData: HeroSlideData[] = [");
  for (const r of records) {
    lines.push(`  { file: ${JSON.stringify(r.slug)}, project: ${JSON.stringify(r.title)}, client: ${JSON.stringify(r.client)} },`);
  }
  lines.push("];");
  lines.push("");

  fs.writeFileSync(DATA_OUT, lines.join("\n"));
  console.log(`Copied ${records.length} hero images, wrote ${DATA_OUT}`);
}

main();
