// Hero slide text data. Generated by scripts/import-hero.mjs, then hand-edited.
// Add a future slide: drop NN TITLE - CLIENT NAME.jpg into IntroSlider/2048,
// re-run the importer, and re-check the order/text below.
// projectSlug links a slide to its entry in projects.data.ts — the hero
// credit block (PROJECT / CLIENT / SCOPE) takes its scope from that
// project's "Scope" credit. scope overrides it per slide.
export interface HeroSlideData {
  file: string;
  project: string;
  client: string;
  projectSlug?: string;
  scope?: string;
}

export const heroSlidesData: HeroSlideData[] = [
  { file: "31-kings-cup-jeddah.jpg", project: "Kings Cup Jeddah", client: "Roland Greil", projectSlug: "kings-cup-opening-ceremony" },
  { file: "30-hongkong-nye.jpg", project: "Hongkong NYE", client: "Roland Greil", projectSlug: "hong-kong-new-year-countdown" },
  { file: "29-acdc-pwr-up-tour-australia.jpg", project: "AC/DC PWR Up Tour Australia", client: "Woodroffe Basset Design", projectSlug: "ac-dc-pwr-up-world-tour" },
  { file: "28-grand-egyptian-museum-opening.jpg", project: "Grand Egyptian Museum Opening", client: "Roland Greil", projectSlug: "opening-of-the-grand-egyptian-museum" },
  { file: "27-madagascar-kids-musical.jpg", project: "Madagascar Kids Musical", client: "Festspielhaus Fuessen", projectSlug: "madagascar-kids-musical" },
  { file: "26-ozzy-osbourne-back-to-the-beginning.jpg", project: "Ozzy Osbourne Back to the Beginning", client: "Woodroffe Basset Design", projectSlug: "ozzy-osbourne-back-to-the-beginning" },
  { file: "25-vorwerk-ceremony.jpg", project: "Vorwerk Ceremony", client: "Projektstark", projectSlug: "vorwerk-win-when-you-swing" },
  { file: "24-company-aniversary-pitch.jpg", project: "Company Aniversary Pitch", client: "Roland Greil", projectSlug: "company-anniversary" },
  { file: "23-die-paepstin.jpg", project: "Die Paepstin", client: "Festspielhaus Fuessen", projectSlug: "die-paepstin" },
  { file: "22-geist-der-weihnacht.jpg", project: "Geist Der Weihnacht", client: "Festspielhaus Fuessen", projectSlug: "geist-der-weihnacht-musical-theater" },
  { file: "21-cro-chronicles-tour.jpg", project: "Cro Chronicles Tour", client: "Roland Greil", projectSlug: "cro-chronicles-tour" },
  { file: "20-arab-gulf-cup.jpg", project: "Arab Gulf Cup", client: "Roland Greil", projectSlug: "arab-gulf-cup-opening-ceremony" },
  { file: "19-fc-pro-worldchampionships.jpg", project: "FC Pro Worldchampionships", client: "David Bishop", projectSlug: "fc-pro-world-championship" },
  { file: "18-apefest.jpg", project: "Apefest", client: "Roland Greil", projectSlug: "apefest-2024" },
  { file: "17-bayerischer-filmpreis.jpg", project: "Bayerischer Filmpreis", client: "BR", projectSlug: "bayerischer-filmpreis-2" },
  { file: "16-asia-cup-doha.jpg", project: "Asia Cup Doha", client: "Roland Greil", projectSlug: "asia-cup-2024" },
  { file: "15-longines-global-champions-ryhad.jpg", project: "Longines Global Champions Ryhad", client: "Roland Greil", projectSlug: "longines-global-champions-tour-closing" },
  { file: "14-circle-of-light.jpg", project: "Circle of Light", client: "Jerry Appelt", scope: "Lighting Programming" },
  { file: "13-audi-etron-clt.jpg", project: "Audi Etron CLT", client: "Audi AG", scope: "Lighting Design" },
  { file: "12-klangwolke-linz.jpg", project: "Klangwolke Linz", client: "Roland Greil", projectSlug: "klangwolke-linz" },
  { file: "11-apache-tour.jpg", project: "Apache Tour", client: "Roland Greil" },
  { file: "10-bavaria-sounds.jpg", project: "Bavaria Sounds", client: "Roland Greil", projectSlug: "bavaria-sounds" },
  { file: "09-musikhelden.jpg", project: "Musikhelden", client: "Systemprovider", projectSlug: "musikhelden" },
  { file: "08-starmania.jpg", project: "Starmania", client: "Roland Greil", projectSlug: "orf-starmania" },
  { file: "07-geist-der-weihnacht.jpg", project: "Geist Der Weihnacht", client: "Festspielhaus Fuessen", projectSlug: "geist-der-weihnacht-musical-theater" },
  { file: "06-romeo-and-juliet.jpg", project: "Romeo and Juliet", client: "Roland Greil", scope: "Lighting Programmer" },
  { file: "05-romeo-and-juliet.jpg", project: "Romeo and Juliet", client: "Roland Greil", scope: "Lighting Programmer" },
  { file: "04-brandner-kasper.jpg", project: "Brandner Kasper", client: "Charly Pauli", projectSlug: "brandner-kasper-2019" },
  { file: "03-audi-a5-reveal-china.jpg", project: "Audi A5 Reveal China", client: "Amir Vaziri", scope: "Lighting Design" },
  { file: "02-sony-booth-at-ifa.jpg", project: "Sony Booth at IFA", client: "Freestate", projectSlug: "sony-at-ifa" },
  { file: "01-samsung-booth-at-ces.jpg", project: "Samsung Booth at CES", client: "Freestate", projectSlug: "samsung-at-ces" },
];
