// Hero slide text data. Generated by scripts/import-hero.mjs, then hand-edited.
// Add a future slide: drop NN TITLE - CLIENT NAME.jpg into IntroSlider/2048,
// re-run the importer, and re-check the order/text below.
export interface HeroSlideData {
  file: string;
  project: string;
  client: string;
}

export const heroSlidesData: HeroSlideData[] = [
  { file: "31-kings-cup-jeddah.jpg", project: "Kings Cup Jeddah", client: "Roland Greil" },
  { file: "30-hongkong-nye.jpg", project: "Hongkong NYE", client: "Roland Greil" },
  { file: "29-acdc-pwr-up-tour-australia.jpg", project: "AC/DC PWR Up Tour Australia", client: "Woodroffe Basset Design" },
  { file: "28-grand-egyptian-museum-opening.jpg", project: "Grand Egyptian Museum Opening", client: "Roland Greil" },
  { file: "27-madagascar-kids-musical.jpg", project: "Madagascar Kids Musical", client: "Festspielhaus Fuessen" },
  { file: "26-ozzy-osbourne-bttb.jpg", project: "Ozzy Osbourne Bttb", client: "Woodroffe Basset Design" },
  { file: "25-vorwerk-ceremony.jpg", project: "Vorwerk Ceremony", client: "Projektstark" },
  { file: "24-company-aniversary-pitch.jpg", project: "Company Aniversary Pitch", client: "Roland Greil" },
  { file: "23-die-paepstin.jpg", project: "Die Paepstin", client: "Festspielhaus Fuessen" },
  { file: "22-geist-der-weihnacht.jpg", project: "Geist Der Weihnacht", client: "Festspielhaus Fuessen" },
  { file: "21-cro-chronicles-tour.jpg", project: "Cro Chronicles Tour", client: "Roland Greil" },
  { file: "20-arab-gulf-cup.jpg", project: "Arab Gulf Cup", client: "Roland Greil" },
  { file: "19-fc-pro-worldchampionships.jpg", project: "FC Pro Worldchampionships", client: "David Bishop" },
  { file: "18-apefest.jpg", project: "Apefest", client: "Roland Greil" },
  { file: "17-bayerischer-filmpreis.jpg", project: "Bayerischer Filmpreis", client: "BR" },
  { file: "16-asia-cup-doha.jpg", project: "Asia Cup Doha", client: "Roland Greil" },
  { file: "15-longines-global-champions-ryhad.jpg", project: "Longines Global Champions Ryhad", client: "Roland Greil" },
  { file: "14-circle-of-light.jpg", project: "Circle of Light", client: "Jerry Appelt" },
  { file: "13-audi-etron-clt.jpg", project: "Audi Etron CLT", client: "Audi" },
  { file: "12-klangwolke-linz.jpg", project: "Klangwolke Linz", client: "Roland Greil" },
  { file: "11-apache-tour.jpg", project: "Apache Tour", client: "Roland Greil" },
  { file: "10-bavaria-sounds.jpg", project: "Bavaria Sounds", client: "Roland Greil" },
  { file: "09-musikhelden.jpg", project: "Musikhelden", client: "Systemprovider" },
  { file: "08-starmania.jpg", project: "Starmania", client: "Roland Greil" },
  { file: "07-geist-der-weihnacht.jpg", project: "Geist Der Weihnacht", client: "Festspielhaus Fuessen" },
  { file: "06-romeo-and-juliet.jpg", project: "Romeo and Juliet", client: "Roland Greil" },
  { file: "05-romeo-and-juliet.jpg", project: "Romeo and Juliet", client: "Roland Greil" },
  { file: "04-brandner-kasper.jpg", project: "Brandner Kasper", client: "Charly Pauli" },
  { file: "03-audi-a5-reveal-china.jpg", project: "Audi A5 Reveal China", client: "Amir Vaziri" },
  { file: "02-sony-booth-at-ifa.jpg", project: "Sony Booth at IFA", client: "Freestate" },
  { file: "01-samsung-booth-at-ces.jpg", project: "Samsung Booth at CES", client: "Freestate" },
];
